PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS ryp_payment_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  agent_id TEXT NOT NULL,
  sales_id TEXT NOT NULL,
  branch_code TEXT NOT NULL,
  policy_no TEXT NOT NULL,
  policy_type TEXT,
  plan_code TEXT,
  plan_name TEXT,
  sum NUMERIC,
  payment_mode TEXT,
  total_premium NUMERIC NOT NULL DEFAULT 0,
  pay_year TEXT,
  endowment_year TEXT,
  effective_date TEXT,
  due_date TEXT,
  meta_data TEXT,
  customer_full_name TEXT NOT NULL,
  customer_mobile_no TEXT,
  customer_email TEXT,
  customer_address TEXT,
  payment_status TEXT NOT NULL CHECK (payment_status IN ('PENDING_FINANCE','SUCCESS','FAILED')),
  payment_type TEXT,
  payment_type_desc TEXT,
  pay_date TEXT NOT NULL,
  collection_id TEXT NOT NULL,
  trx_id TEXT,
  reference1 TEXT,
  reference2 TEXT,
  reference3 TEXT,
  create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_user_code TEXT,
  last_update TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_code TEXT,
  UNIQUE(agent_id, sales_id, policy_no, collection_id)
);

CREATE TABLE IF NOT EXISTS ryp_payment_transaction (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ryp_payment_history_id INTEGER NOT NULL,
  policy_no TEXT NOT NULL,
  collection_id TEXT NOT NULL,
  terminal_id TEXT,
  trx_id TEXT,
  uuid TEXT,
  reference1 TEXT,
  reference2 TEXT,
  reference3 TEXT,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  response_code TEXT,
  payment_type TEXT,
  payment_type_desc TEXT,
  payment_code TEXT,
  pay_date TEXT,
  qr_code_base64 TEXT,
  qr_create_date TEXT,
  qr_expire_date TEXT,
  merchant_id TEXT,
  customer_id TEXT,
  charge_id TEXT,
  credit_card_no TEXT,
  credit_card_token TEXT,
  slip_file TEXT,
  module_type TEXT,
  create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_user_code TEXT,
  last_update TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_code TEXT,
  FOREIGN KEY (ryp_payment_history_id) REFERENCES ryp_payment_history(id)
);

CREATE TABLE IF NOT EXISTS ryp_payment_detail (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ryp_payment_transaction_id INTEGER NOT NULL,
  policy_no TEXT NOT NULL,
  pay_period TEXT,
  sequence INTEGER,
  collection_id TEXT NOT NULL,
  rp_no TEXT,
  submit_no TEXT,
  life_premium NUMERIC NOT NULL DEFAULT 0,
  rider_premium NUMERIC NOT NULL DEFAULT 0,
  rsp_premium NUMERIC NOT NULL DEFAULT 0,
  extra_premium NUMERIC NOT NULL DEFAULT 0,
  topup_premium NUMERIC NOT NULL DEFAULT 0,
  total_premium NUMERIC NOT NULL DEFAULT 0,
  apl_amount NUMERIC NOT NULL DEFAULT 0,
  total_amount NUMERIC NOT NULL DEFAULT 0,
  create_time TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_user_code TEXT,
  last_update TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_user_code TEXT,
  FOREIGN KEY (ryp_payment_transaction_id) REFERENCES ryp_payment_transaction(id)
);

CREATE INDEX IF NOT EXISTS idx_history_search ON ryp_payment_history(customer_full_name, policy_no);
CREATE INDEX IF NOT EXISTS idx_history_pay_date ON ryp_payment_history(pay_date DESC);
CREATE INDEX IF NOT EXISTS idx_transaction_history ON ryp_payment_transaction(ryp_payment_history_id);
CREATE INDEX IF NOT EXISTS idx_detail_transaction ON ryp_payment_detail(ryp_payment_transaction_id);
